# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Fiber Optic Now
tagline:	Fiber Optic Now
description:	'Fiber Optic Now'
url:		http://fiberopticnow.github.io

author:
  name:		'Katie Williams, M.Ed.'
  url:		https://google.com/+IanCamporezBrunelli

paginate:	5

# Custom vars
icon:		/assets/images/icon.jpg
cover:	/assets/images/white.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/fiberopticnow
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/fiberopticnow
    desc:	Fork me on github

  - icon:	linkedin-alt
    url:	https://nl.linkedin.com/in/fiberopticnow/
    desc:	Add me on LinkedIn

  - icon:	feed
    url:	http://fiberopticnow.github.io/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	http://fiberopticnow.github.io
    
  - title:	About
    url:	http://fiberopticnow.github.io/about
    
copyright:
  author:	Katie Williams
  url:		http://fiberopticnow.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
